// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PushNotification.Configuracao;

#nullable disable

namespace PushNotification.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240122115907_InscricaoUsuario")]
    partial class InscricaoUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PushNotification.Models.Inscricao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<Guid>("aparelho")
                        .HasColumnType("uuid")
                        .HasColumnName("aparelho");

                    b.Property<string>("auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("p26dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p26dh");

                    b.Property<int?>("usuario_id")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("endpoint")
                        .IsUnique();

                    b.HasIndex("usuario_id");

                    b.ToTable("Inscricao");
                });

            modelBuilder.Entity("PushNotification.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PushNotification.Models.Inscricao", b =>
                {
                    b.HasOne("PushNotification.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
